### ISSUE TITLE
Can't run example because of import problem (No module named 'test_needle')

### ISSUE THREAD

**Issue by samuraii** [jlane9/pytest-needle#15]
## Expected Behavior
All works fine.

## Actual Behavior
```
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\test\env\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\dev\test\env\lib\site-packages\_pytest\config\__init__.py", line 56, in main
    config = _prepareconfig(args, plugins)
  File "c:\dev\test\env\lib\site-packages\_pytest\config\__init__.py", line 181, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\dev\test\env\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\dev\test\env\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\dev\test\env\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\dev\test\env\lib\site-packages\pluggy\callers.py", line 196, in _multicall
    gen.send(outcome)
  File "c:\dev\test\env\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\dev\test\env\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\dev\test\env\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\dev\test\env\lib\site-packages\_pytest\config\__init__.py", line 607, in pytest_cmdline_parse
    self.parse(args)
  File "c:\dev\test\env\lib\site-packages\_pytest\config\__init__.py", line 772, in parse
    self._preparse(args, addopts=addopts)
  File "c:\dev\test\env\lib\site-packages\_pytest\config\__init__.py", line 724, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\dev\test\env\lib\site-packages\pluggy\__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\dev\test\env\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\dev\test\env\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\dev\test\env\lib\site-packages\_pytest\assertion\rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "c:\dev\test\env\lib\site-packages\pytest_needle\plugin.py", line 11, in <module>
    from pytest_needle.driver import DEFAULT_BASELINE_DIR, DEFAULT_OUTPUT_DIR, DEFAULT_ENGINE, \
  File "c:\dev\test\env\lib\site-packages\_pytest\assertion\rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "c:\dev\test\env\lib\site-packages\pytest_needle\driver.py", line 14, in <module>
    from test_needle.cases import import_from_string
ModuleNotFoundError: No module named 'test_needle'
```

## Steps to Reproduce the Problem

  1. Follow the tutorial example steps

## Specifications

  - Version: python 3.6
  - Platform: win10

**Comment by jlane9** [comment]
@samuraii I've been looking into this and I can't figure out why the module it's referencing is test_needle. In master and the latest version (0.3.8) it is `needle.cases` not `test_needle.cases`. Here's where your stack trace says it should be failing https://github.com/jlane9/pytest-needle/blob/master/pytest_needle/driver.py#L14. What version of needle/pytest-needle are you running?

**Comment by samuraii** [comment]
Hi, I have just repeated the tutorial on my mac from scratch and it worked. There is no reason I can understand why the import behavior is so weired on win10. I will try it one more time, but I can say that the version is the one which is installed by "pip install pytest-needle"

**Comment by samuraii** [comment]
well, finally that worked, maybe I've missed something
